## a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [5]:
np.negative(a)
len(a[a<0])

4

### 2. How many positive numbers are there?

In [4]:
np.positive(a)
len(a[a>0])

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 3. How many even positive numbers are there?

In [10]:
b= a[a>0]
b % 2 == 0
np.sum(b % 2 ==0)

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [9]:
len(a[(a+3)>0])

10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [7]:
a
a_squared = np.square(a)
new_mean = np.mean(np.square(a))
new_sd = np.std(np.square(a))
print(a_squared)
print(new_mean)
print(new_sd)

[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0
144.0243035046516


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [13]:
a
print(a.mean())
center_function = lambda x: x - x.mean()
data_centered = center_function(a)
print(data_centered)
print(data_centered.mean())

3.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
0.0


### 7. Calculate the z-score for each data point.

In [16]:
import scipy.stats as stats
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
zscores = stats.zscore(a)
print(zscores)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [31]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [38]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [42]:
sum_of_a = print(sum(a))

55


### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [43]:
min_of_a = min(a)

1


### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [44]:
max_of_a = max(a)

10


### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [46]:
mean_of_a = np.mean(a)

5.5


### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [47]:
product_of_a = np.prod(a)

3628800


### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [48]:
squares_of_a = np.square(a)

[  1   4   9  16  25  36  49  64  81 100]


 ### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [63]:
# create a numpy array
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ar)
odds_in_a = ar[ar % 2 != 0]
print (f'Here are the odds: {odds_in_a}')

[ 1  2  3  4  5  6  7  8  9 10]
Here are the odds: [1 3 5 7 9]


### Make a variable named evens_in_a. It should hold only the evens

In [64]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ar)
evens_in_a = ar[ar % 2 == 0]
print (f'Here are the evens: {evens_in_a}')

[ 1  2  3  4  5  6  7  8  9 10]
Here are the evens: [ 2  4  6  8 10]


### Testing Scipy for exercise  7 (z-scores)

In [65]:
import scipy.stats as stats

In [66]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [67]:
zscores = stats.zscore(a)

In [68]:
zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [27]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b = np.array(b)

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [28]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [29]:
sum_of_b

33

In [30]:
## Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [31]:
b.min()

3

In [32]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [34]:
b.max()

8

In [35]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
b.mean()

5.5

In [38]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
np.prod(b)

20160

In [39]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        


In [40]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)