## a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [3]:
np.negative(a)

array([ -4, -10, -12, -23,   2,   1,   0,   0,   0,   6,  -3,   7])

### 2. How many positive numbers are there?

In [4]:
np.positive(a)

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 3. How many even positive numbers are there?

In [5]:
b= a[a>0]
b % 2 == 0
np.sum(b % 2 ==0)

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [6]:
b = a + 3
np.positive(b)
print(np.sum(b>0))

10


### 5. If you squared each number, what would the new mean and standard deviation be?

In [7]:
a
a_squared = np.square(a)
new_mean = np.mean(np.square(a))
new_sd = np.std(np.square(a))
print(a_squared)
print(new_mean)
print(new_sd)

[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0
144.0243035046516


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [8]:
a
print(a.mean())
center_function = lambda x: x - x.mean()
data_centered = center_function(a)
print(data_centered)
print(data_centered.mean())

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 7. Calculate the z-score for each data point.

In [41]:
print (a)
mean = np.mean(a)
std = np.std(a)
print('mean of the dataset is', mean)
print('std. deviation is', std)


z_scores = (a-np.mean(a) / np.std(a))
print (z_scores)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mean of the dataset is 5.5
std. deviation is 2.8722813232690143
[-0.91485422  0.08514578  1.08514578  2.08514578  3.08514578  4.08514578
  5.08514578  6.08514578  7.08514578  8.08514578]


### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [31]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [38]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [42]:
sum_of_a = print(sum(a))

55


### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [43]:
min_of_a = print(min(a))

1


### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [44]:
max_of_a = print(max(a))

10


### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [46]:
mean_of_a = print(np.mean(a))

5.5


### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [47]:
product_of_a = print(np.prod(a))

3628800


### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [48]:
squares_of_a = print(np.square(a))

[  1   4   9  16  25  36  49  64  81 100]


 ### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [63]:
# create a numpy array
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ar)
odds_in_a = ar[ar % 2 != 0]
print (f'Here are the odds: {odds_in_a}')

[ 1  2  3  4  5  6  7  8  9 10]
Here are the odds: [1 3 5 7 9]


### Make a variable named evens_in_a. It should hold only the evens

In [64]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ar)
evens_in_a = ar[ar % 2 == 0]
print (f'Here are the evens: {evens_in_a}')

[ 1  2  3  4  5  6  7  8  9 10]
Here are the evens: [ 2  4  6  8 10]


### Testing Scipy for exercise  7 (z-scores)

In [65]:
import scipy.stats as stats

In [66]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [67]:
zscores = stats.zscore(a)

In [68]:
zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])